export default  {
  login: "BINARY-TECH001",
  id: 87129632,
  node_id: "MDQ6VXNlcjg3MTI5NjMy",
  avatar_url: "https://avatars.githubusercontent.com/u/87129632?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/BINARY-TECH001",
  html_url: "https://github.com/BINARY-TECH001",
  followers_url: "https://api.github.com/users/BINARY-TECH001/followers",
  following_url:
    "https://api.github.com/users/BINARY-TECH001/following{/other_user}",
  gists_url: "https://api.github.com/users/BINARY-TECH001/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/BINARY-TECH001/starred{/owner}{/repo}",
  subscriptions_url:
    "https://api.github.com/users/BINARY-TECH001/subscriptions",
  organizations_url: "https://api.github.com/users/BINARY-TECH001/orgs",
  repos_url: "https://api.github.com/users/BINARY-TECH001/repos",
  events_url: "https://api.github.com/users/BINARY-TECH001/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/BINARY-TECH001/received_events",
  type: "User",
  site_admin: false,
  name: "ABDULRAFIU MUBARAK I ",
  company: "Binary Tech",
  blog: "https://binaryportfolio.netlify.app",
  location: "12,kola sanusi street,Mabolaje area oyo,oyo state,Nigeria",
  email: null,
  hireable: null,
  bio: "Fullstack Developer || Javascript || React || Node || PHP || Express || MySQL",
  twitter_username: "binaryTech001",
  public_repos: 31,
  public_gists: 0,
  followers: 4,
  following: 9,
  created_at: "2021-07-08T11:58:33Z",
  updated_at: "2022-12-05T13:02:34Z",
};