export default [
  {
    login: "AbdeenM",
    id: 24494653,
    node_id: "MDQ6VXNlcjI0NDk0NjUz",
    avatar_url: "https://avatars.githubusercontent.com/u/24494653?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/AbdeenM",
    html_url: "https://github.com/AbdeenM",
    followers_url: "https://api.github.com/users/AbdeenM/followers",
    following_url:
      "https://api.github.com/users/AbdeenM/following{/other_user}",
    gists_url: "https://api.github.com/users/AbdeenM/gists{/gist_id}",
    starred_url: "https://api.github.com/users/AbdeenM/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/AbdeenM/subscriptions",
    organizations_url: "https://api.github.com/users/AbdeenM/orgs",
    repos_url: "https://api.github.com/users/AbdeenM/repos",
    events_url: "https://api.github.com/users/AbdeenM/events{/privacy}",
    received_events_url: "https://api.github.com/users/AbdeenM/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "jerryOluranti",
    id: 61914867,
    node_id: "MDQ6VXNlcjYxOTE0ODY3",
    avatar_url: "https://avatars.githubusercontent.com/u/61914867?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/jerryOluranti",
    html_url: "https://github.com/jerryOluranti",
    followers_url: "https://api.github.com/users/jerryOluranti/followers",
    following_url:
      "https://api.github.com/users/jerryOluranti/following{/other_user}",
    gists_url: "https://api.github.com/users/jerryOluranti/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/jerryOluranti/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/jerryOluranti/subscriptions",
    organizations_url: "https://api.github.com/users/jerryOluranti/orgs",
    repos_url: "https://api.github.com/users/jerryOluranti/repos",
    events_url: "https://api.github.com/users/jerryOluranti/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/jerryOluranti/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "Owoade",
    id: 63651250,
    node_id: "MDQ6VXNlcjYzNjUxMjUw",
    avatar_url: "https://avatars.githubusercontent.com/u/63651250?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Owoade",
    html_url: "https://github.com/Owoade",
    followers_url: "https://api.github.com/users/Owoade/followers",
    following_url: "https://api.github.com/users/Owoade/following{/other_user}",
    gists_url: "https://api.github.com/users/Owoade/gists{/gist_id}",
    starred_url: "https://api.github.com/users/Owoade/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/Owoade/subscriptions",
    organizations_url: "https://api.github.com/users/Owoade/orgs",
    repos_url: "https://api.github.com/users/Owoade/repos",
    events_url: "https://api.github.com/users/Owoade/events{/privacy}",
    received_events_url: "https://api.github.com/users/Owoade/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "officialjoegith",
    id: 90398840,
    node_id: "MDQ6VXNlcjkwMzk4ODQw",
    avatar_url: "https://avatars.githubusercontent.com/u/90398840?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/officialjoegith",
    html_url: "https://github.com/officialjoegith",
    followers_url: "https://api.github.com/users/officialjoegith/followers",
    following_url:
      "https://api.github.com/users/officialjoegith/following{/other_user}",
    gists_url: "https://api.github.com/users/officialjoegith/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/officialjoegith/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/officialjoegith/subscriptions",
    organizations_url: "https://api.github.com/users/officialjoegith/orgs",
    repos_url: "https://api.github.com/users/officialjoegith/repos",
    events_url: "https://api.github.com/users/officialjoegith/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/officialjoegith/received_events",
    type: "User",
    site_admin: false,
  },
];
